# Generated by Django 6.1 on 2026-09-21 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('poultry_type', models.CharField(choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('SONALI', 'Sonali'), ('OTHER', 'Other')], max_length=10)),
                ('start_date', models.DateField()),
                ('initial_bird_count', models.PositiveIntegerField()),
                ('purchase_price_per_bird', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('farm_type', models.CharField(choices=[('BROILER', 'Broiler'), ('LAYER', 'Layer'), ('SONALI', 'Sonali'), ('MIXED', 'Mixed')], max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FARM', 'Farm'), ('BATCH', 'Batch')], max_length=5)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='poultry.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='poultry.farm')),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='poultry.farm'),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('POULTRY', 'Poultry'), ('EGG', 'Egg')], max_length=10)),
                ('unit', models.CharField(choices=[('BIRD', 'Bird'), ('EGG', 'Egg')], max_length=5)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poultry.batch')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='poultry.farm')),
            ],
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('feed_amount_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('water_liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dead_count', models.PositiveIntegerField(default=0)),
                ('sick_count', models.PositiveIntegerField(default=0)),
                ('medicine_used', models.BooleanField(default=False)),
                ('medicine_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='poultry.batch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'record_date'), name='unique_daily_record_per_batch_date')],
            },
        ),
        migrations.CreateModel(
            name='EggProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('egg_count', models.PositiveIntegerField()),
                ('damaged_egg_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egg_productions', to='poultry.batch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('batch', 'production_date'), name='unique_egg_production_per_batch_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_farm_name_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('farm', 'code'), name='unique_batch_code_per_farm'),
        ),
    ]
